PrimeFaces.locales ['fr'] = {
                closeText: 'Fermer',
                prevText: 'Precedent',
                nextText: 'Suivant',
                monthNames: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre' ],
                monthNamesShort: ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aou', 'Sep', 'Oct', 'Nov', 'Dec' ],
                dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
                dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
                dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
                weekHeader: 'Semaine',
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix:'',
                timeOnlyTitle: 'Choisir l\'heure',
                timeText: 'Heure',
                hourText: 'Heures',
                minuteText: 'Minutes',
                secondText: 'Secondes',
                currentText: 'Auj.',
                ampm: false,
                month: 'Mois',
                week: 'Semaine',
                day: 'Jour',
                allDayText: 'Toute la journee'
            };